pipeline {
    agent { docker { image 'maven:3.3.3' } }
      stages {
        stage('build jar file using maven') {
      steps {
        sh 'pwd'
        dir ("complete") {
          sh 'pwd && ./mvnw package' 
        }
        sh 'pwd'
      }
    }
  }
}
