pipeline {
    agent { docker { image 'maven:3.3.3' } }
      stages {
        stage('build jar file using maven') {
      steps {
        cd gs-spring-boot-docker/complete
        ./mvnw package
        java -jar target/spring-boot-docker-complete-0.0.1-SNAPSHOT.jar
      }
    }
  }
}
